version: "3.9"

services:
  app: 
    image: app:php_8.0-fpm
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./src/:/var/www:cached

  web: 
    image: web:nginx_1.20-alpine
    build: 
      context: .
      dockerfile: ./docker/web/Dockerfile
    container_name: web
    ports: 
      - 8080:80
      # - 443:443
    volumes: 
      - ./src:/var/www:cached
    depends_on: 
      - app  

  db:
    image: db:mysql_8.0
    container_name: db
    build: 
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: training
      MYSQL_USER: trainingUser
      MYSQL_PASSWORD: testpassword@
      MYSQL_ROOT_PASSWORD: testpassword@
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:

#   mysql:
#     build: "./.docker/mysql"
#     ports:
#     - "3306:3306"
#     volumes:
#     - "./storage/mysql:/var/lib/mysql"
#     environment:
#     MYSQL_DATABASE: sumune
#     MYSQL_USER: root
#     MYSQL_PASSWORD: rootroot
#     MYSQL_ROOT_PASSWORD: rootroot
#     container_name: sumune-mysql