version: "3.9"

services:
  app: 
    image: app:php_8.0-fpm
    container_name: app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./src/:/var/www:cached

  web: 
    image: web:nginx_1.20-alpine
    build: 
      context: .
      dockerfile: ./docker/web/Dockerfile
    container_name: web
    ports: 
      - 8080:80
      # - 443:443
    volumes: 
      - ./src:/var/www:cached
    depends_on: 
      - app  

  db:
    image: db:mysql_8.0
    container_name: db
    build: 
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: training
      MYSQL_USER: user
      MYSQL_PASSWORD: hoge
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin

  phpmyadmin:
    platform: 'linux/amd64'
    container_name: test_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=db
    # - PMA_USER=user
    # - PMA_PASSWORD=hoge
    ports:
    - 3000:80
    depends_on:
      - db
volumes:
  mysql-volume: